### PR TITLE
[12.0] Encode/decode date and datetime in redis sessions

### PR DESCRIPTION
**Pull request by guewen**
Backport of #178

### CODE REVIEW

**Review by PCatinean — APPROVED** [review]

**Comment by PCatinean** [comment]
Why are the tests stalling?

**Comment by PCatinean** [comment]
@guewen is there any way we can fastforward this PR and https://github.com/camptocamp/odoo-cloud-platform/pull/185 ?

**Comment by guewen** [comment]
> Why are the tests stalling?

The build is green on [travis](https://travis-ci.com/github/camptocamp/odoo-cloud-platform/builds/168180473) anyway, merging

**Comment by PCatinean** [comment]
Thank you Guewen :pray:

**Pull request merged**
