### PR TITLE
Object Storage - inactive mode

### PR DESCRIPTION
**Pull request by yankinmax**
Forward port of:
- https://github.com/camptocamp/odoo-cloud-platform/pull/364

### CODE REVIEW

**Comment by sebalix** [comment]
@yankinmax thank you for keeping this 15.0 PR up-to-date with the 14.0 one :)

**Comment by yankinmax** [comment]
@sebalix I need it for my migrations as well:)

**Comment by yankinmax** [comment]
**UPDATED**
With last changes made in v14 PR => https://github.com/camptocamp/odoo-cloud-platform/pull/364
Checked on two customers projects

**Review by StephaneMangin — APPROVED** [review]
LG

**Review by sebalix — APPROVED** [review]

**Pull request merged**
