### PR TITLE
[13.0] attachment_swift: multi-tenancy use db name in container

### PR DESCRIPTION
**Pull request by dannyadair**
Adds the possibility to insert `{db}` placeholder in the container
name that will be replaced by the database name to form a unique
container name per database.

### CODE REVIEW

**Comment by dannyadair** [comment]
Hello @yvaucher sorry my first PR in here, anything else I need to provide? Cheers

**Review by yvaucher — APPROVED** [review]
LGTM

**Comment by yvaucher** [comment]
Thanks for the improvement (and for your patience :sweat_smile: )

**Comment by dannyadair** [comment]
Thank you very much!
Spooky timing - I needed it today :)
Using upstream as-is is always nicer

**Pull request merged**
